name: CI
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
env:
  DB_USERNAME: ${{secrets.DB_USERNAME}}
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
  DB_HOST: 127.0.0.1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Start MySql
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"
      - run: |
         mysql -u root -e "CREATE DATABASE IF NOT EXISTS investor_db;"
         mysql -u root -e "CREATE USER '${DB_USERNAME}'@'%' IDENTIFIED BY '${DB_PASSWORD}';"
         mysql -u root -e "GRANT ALL PRIVILEGES ON investor_db.* TO '${DB_USERNAME}'@'%';"
      - name: Build, unit and integration tests
        run: mvn -B verify
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/investor:$IMAGE_TAG .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/investor:$IMAGE_TAG ${{secrets.DOCKERHUB_USERNAME }}/investor:latest

      - name: Push Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/investor:$IMAGE_TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/investor:latest
